'use client';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { ArrowRight, CalendarBlank, CheckCircle, Columns, FolderSimple, ListBullets, MagnifyingGlass, Plus, WarningCircle } from './icons';
import { useState, type FormEvent } from 'react';
import { useDemo } from './demo-provider';
import { StatusBadge } from './status-badge';
import { dueSoon, filterProjects, formatDate, isOverdue, paginate, projectMetrics, projectStatuses, statusLabels, type Project, type ProjectStatus } from '@/lib/projects';

export function DeadlineRail() {
  const {projects,today,clients}=useDemo();
  const upcoming=projects.filter(p=>dueSoon(p,today)).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));
  return <aside className="deadline-rail" aria-label="Upcoming deadlines"><div className="rail-title"><CalendarBlank size={19} aria-hidden="true"/><h2>On the horizon</h2></div><p className="muted small">Due in the next 7 days</p>{upcoming.length ? <ol className="deadline-list">{upcoming.map(p=><li key={p.id}><div className="date-block"><strong>{p.dueDate.slice(8)}</strong><span>SEP</span></div><div><Link href={`/demo/projects/${p.id}`}>{p.name}</Link><p>{clients.find(c=>c.id===p.clientId)?.name}</p></div></li>)}</ol>:<p className="empty-rail">A little breathing room. No projects due in the next 7 days.</p>}<div className="rail-tip"><span className="eyebrow">A SMALL REMINDER</span><h3>Clarity keeps things moving.</h3><p>Keep deadlines and project statuses current so the next step is always clear.</p><span className="decorative-lines" aria-hidden="true"><i/><i/><i/></span></div></aside>;
}
export function MetricStrip() {
  const {projects,today}=useDemo(); const m=projectMetrics(projects,today);
  const metrics=[{label:'In progress',value:m.active,note:'Projects in motion',icon:FolderSimple,href:'/demo/projects?status=active'}, {label:'In review',value:m.review,note:'Ready for a second look',icon:CheckCircle,href:'/demo/projects?status=review'}, {label:'Due this week',value:m.dueSoon,note:'Today through the next 7 days',icon:CalendarBlank,href:'/demo'}, {label:'Needs attention',value:m.overdue,note:'Open projects past their deadline',icon:WarningCircle,href:'/demo/projects?attention=1'}];
  return <div className="metric-strip">{metrics.map(({label,value,note,icon:Icon,href})=><Link className="metric" href={href} key={label}><div className="metric-label"><span>{label}</span><Icon size={18} aria-hidden="true"/></div><strong className={label==='Needs attention'&&value?'warning-number':''}>{value.toString().padStart(2,'0')}</strong><span className="metric-note">{note}</span></Link>)}</div>;
}
function ProjectCard({project}: {project: Project}) {
  const {clients,today,save}=useDemo(); const [error,setError]=useState(''); const c=clients.find(c=>c.id===project.clientId);
  return <article className="project-card"><div className="card-client"><span className={`client-avatar ${c?.color}`}>{c?.initials}</span><span>{c?.name}</span></div><Link className="project-title" href={`/demo/projects/${project.id}`}>{project.name}</Link><p>{project.description}</p><div className={`card-deadline ${isOverdue(project,today)?'overdue':''}`}><CalendarBlank size={15} aria-hidden="true"/>{formatDate(project.dueDate)}{isOverdue(project,today)&&<span> · Overdue</span>}</div><label className="sr-only" htmlFor={`status-${project.id}`}>Status for {project.name}</label><select id={`status-${project.id}`} value={project.status} onChange={e=>{const r=save({...project,status:e.target.value},project.id,project.version);setError(r.ok?'':r.message);}}>{projectStatuses.map(s=><option key={s} value={s}>{statusLabels[s]}</option>)}</select>{error&&<p role="alert" className="field-error">{error}</p>}</article>;
}
export function ProjectWorkbench() {
  const params=useSearchParams(); const {projects,clients,today}=useDemo();
  const rawStatus=params.get('status')??'all'; const status=projectStatuses.includes(rawStatus as ProjectStatus)?rawStatus:'all';
  const q=(params.get('q')??'').slice(0,100); const view=params.get('view')==='board'?'board':'table'; const attention=params.get('attention')==='1';
  const filtered=filterProjects(projects,clients,{q,status,attention},today); const paged=paginate(filtered,Number(params.get('page')??1));
  function href(updates: Record<string,string>) { const next=new URLSearchParams(params.toString()); next.delete('page'); for(const [k,v] of Object.entries(updates)){if(v)next.set(k,v);else next.delete(k);}return `/demo/projects${next.size?'?'+next.toString():''}`; }
  function search(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data=new FormData(e.currentTarget); window.history.pushState(null,'',href({q:String(data.get('q')??'').trim()})); }
  return <>
    <div className="page-heading"><div><span className="eyebrow">THE BIG PICTURE, DOWN TO THE DETAILS</span><h1>Projects</h1><p>A little structure. A lot of forward motion.</p></div><Link className="button primary" href="/demo/projects/new"><Plus size={18} aria-hidden="true"/>New project</Link></div>
    <MetricStrip/>
    <div className="workbench-grid"><section className="project-panel" aria-label="Project workbench">
      <nav className="filter-tabs" aria-label="Project status filters"><Link href={href({status:'',attention:''})} aria-current={status==='all'&&!attention?'page':undefined}>All projects <span>{projects.length}</span></Link>{(['active','review','completed','archived'] as const).map(s=><Link key={s} href={href({status:s,attention:''})} aria-current={status===s?'page':undefined}>{statusLabels[s]}<span>{projects.filter(p=>p.status===s).length}</span></Link>)}</nav>
      <div className="project-toolbar"><form key={q} onSubmit={search} className="search-form" role="search"><MagnifyingGlass size={18} aria-hidden="true"/><label className="sr-only" htmlFor="project-search">Search projects or clients</label><input id="project-search" name="q" type="search" defaultValue={q} placeholder="Search projects or clients…" maxLength={100} autoComplete="off"/><button type="submit" aria-label="Search projects"><ArrowRight size={18} aria-hidden="true"/></button></form><div className="view-switch" aria-label="Project view"><Link aria-label="Table view" aria-current={view==='table'?'page':undefined} href={href({view:''})}><ListBullets size={18} aria-hidden="true"/><span>List</span></Link><Link aria-label="Board view" aria-current={view==='board'?'page':undefined} href={href({view:'board'})}><Columns size={18} aria-hidden="true"/><span>Board</span></Link></div></div>
      {(q||attention||rawStatus!==status)&&<div className="active-filters"><span>{attention?'Showing overdue projects':q?`Search: “${q}”`:'Unknown status ignored'}</span><Link href="/demo/projects">Clear filters</Link></div>}
      <div className="sr-only" role="status">{filtered.length} matching projects</div>
      {!filtered.length?<div className="empty-state"><MagnifyingGlass size={30} aria-hidden="true"/><h2>No projects found</h2><p>Try another project or client name, or clear the filters.</p><Link className="button secondary" href="/demo/projects">Clear filters</Link></div>:view==='table'?<div className="table-wrap"><table className="project-table"><caption className="sr-only">Projects in the sample agency workspace</caption><thead><tr><th scope="col">Project name</th><th scope="col" className="client-column">Client</th><th scope="col">Status</th><th scope="col" className="due-column">Due date</th></tr></thead><tbody>{paged.items.map(p=>{const c=clients.find(c=>c.id===p.clientId);return <tr key={p.id}><td><div className="project-name-cell"><span className={`project-symbol ${c?.color}`}><FolderSimple size={19} aria-hidden="true"/></span><div><Link href={`/demo/projects/${p.id}`}>{p.name}</Link><span className="mobile-client">{c?.name}</span></div></div></td><td className="client-column"><span className="table-client"><span className={`client-avatar small-avatar ${c?.color}`}>{c?.initials}</span>{c?.name}</span></td><td><StatusBadge status={p.status}/></td><td className={`due-column ${isOverdue(p,today)?'overdue':''}`}>{formatDate(p.dueDate)}{isOverdue(p,today)&&<span className="overdue-label">Overdue</span>}</td></tr>;})}</tbody></table></div>:<div className="board">{projectStatuses.filter(s=>status==='all'||status===s).map(s=><section className="board-column" key={s} aria-label={`${statusLabels[s]} column`}><div className="board-heading"><StatusBadge status={s}/><span>{paged.items.filter(p=>p.status===s).length}</span></div>{paged.items.filter(p=>p.status===s).map(p=><ProjectCard key={p.id} project={p}/>)}{!paged.items.some(p=>p.status===s)&&<p className="empty-column">No projects on this page</p>}</section>)}</div>}
      <div className="table-footer"><span>{paged.total} {paged.total===1?'project':'projects'}{q||attention||status!=='all'?' matching filters':' in this workspace'}</span><nav aria-label="Pagination"><Link aria-disabled={paged.current===1} tabIndex={paged.current===1?-1:0} href={href({page:String(paged.current-1)})}>Previous</Link><span>{paged.current} / {paged.pages}</span><Link aria-disabled={paged.current===paged.pages} tabIndex={paged.current===paged.pages?-1:0} href={href({page:String(paged.current+1)})}>Next</Link></nav></div>
    </section><DeadlineRail/></div>
    <div className="workbench-footnote"><CheckCircle size={15} aria-hidden="true"/><span>Every count comes from the projects you see. No made-up analytics.</span></div>
  </>;
}
