BEGIN;

CREATE TABLE IF NOT EXISTS api_rate_limits (
  bucket_key text NOT NULL,
  window_start timestamptz NOT NULL,
  request_count integer NOT NULL CHECK (request_count > 0),
  expires_at timestamptz NOT NULL,
  PRIMARY KEY (bucket_key, window_start)
);
CREATE INDEX IF NOT EXISTS api_rate_limits_expires_at_idx
  ON api_rate_limits (expires_at);

DO $$
BEGIN
  CREATE ROLE nl_rate_limiter NOLOGIN;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
REVOKE ALL ON api_rate_limits FROM PUBLIC, nl_query_ro, nl_audit_writer;
GRANT USAGE ON SCHEMA public TO nl_rate_limiter;
GRANT SELECT, INSERT, UPDATE, DELETE ON api_rate_limits TO nl_rate_limiter;

-- The deployment preflight should remove expired buckets periodically; the
-- endpoint itself never needs access to raw IP addresses because bucket keys
-- are keyed hashes generated by the application.

COMMIT;
